export {
  CheckForUpdate,
  ClearToolHistory,
  Decrypt,
  DownloadUpdate,
  GetAllConfigs,
  GetAppName,
  GetAuthor,
  GetAllH5DecryptConfigs,
  GetToolHistory,
  GetToolOrder,
  GetVersion,
  H5Decrypt,
  InstallDownloadedUpdate,
  RecordToolHistory,
  SaveConfig,
  SaveGeneratedImage,
  SaveH5DecryptConfig,
  SaveToolOrder,
} from '../../wailsjs/go/main/App'
