// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearToolHistory():Promise<void>;

export function Decrypt(arg1:main.DecryptRequest):Promise<main.DecryptResponse>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:main.DownloadAsset):Promise<main.DownloadUpdateResponse>;

export function GetAllConfigs():Promise<Array<main.Config>>;

export function GetAppName():Promise<string>;

export function GetAuthor():Promise<string>;

export function GetToolHistory(arg1:number):Promise<Array<main.ToolHistory>>;

export function GetToolOrder():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function InstallDownloadedUpdate(arg1:string):Promise<main.InstallUpdateResponse>;

export function RecordToolHistory(arg1:main.ToolHistory):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveToolOrder(arg1:Array<string>):Promise<void>;
