// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Decrypt(arg1:main.DecryptRequest):Promise<main.DecryptResponse>;

export function DeleteConfig(arg1:string):Promise<void>;

export function GetAllConfigs():Promise<Array<main.Config>>;

export function GetAppName():Promise<string>;

export function GetAuthor():Promise<string>;

export function GetVersion():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;
