// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearToolHistory() {
  return window['go']['main']['App']['ClearToolHistory']();
}

export function Decrypt(arg1) {
  return window['go']['main']['App']['Decrypt'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAllH5DecryptConfigs() {
  return window['go']['main']['App']['GetAllH5DecryptConfigs']();
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetAuthor() {
  return window['go']['main']['App']['GetAuthor']();
}

export function GetToolHistory(arg1) {
  return window['go']['main']['App']['GetToolHistory'](arg1);
}

export function GetToolOrder() {
  return window['go']['main']['App']['GetToolOrder']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function H5Decrypt(arg1) {
  return window['go']['main']['App']['H5Decrypt'](arg1);
}

export function InstallDownloadedUpdate(arg1) {
  return window['go']['main']['App']['InstallDownloadedUpdate'](arg1);
}

export function RecordToolHistory(arg1) {
  return window['go']['main']['App']['RecordToolHistory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveH5DecryptConfig(arg1) {
  return window['go']['main']['App']['SaveH5DecryptConfig'](arg1);
}

export function SaveToolOrder(arg1) {
  return window['go']['main']['App']['SaveToolOrder'](arg1);
}
