// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1) {
  return window['go']['main']['App']['Decrypt'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetAuthor() {
  return window['go']['main']['App']['GetAuthor']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
